/* SPDX-License-Identifier: MIT */
#include "ssh_identity.h"
#include "ff.h"
#include <string.h>

#define KEY_PATH "/ssh.key"
#define TEMP_PATH "/ssh-key.tmp"
#define KEY_BYTES 44
static const uint8_t magic[8] = {'A','2','S','S','H',1,0,0};
static const char *last_error = "SSH host key unavailable";

static uint32_t checksum(const uint8_t *p, size_t size) {
    uint32_t crc = UINT32_MAX;
    while (size--) {
        crc ^= *p++;
        for (unsigned n = 0; n < 8; ++n)
            crc = (crc >> 1) ^ (0xedb88320u & (0u - (crc & 1u)));
    }
    return ~crc;
}

/* 1 valid, 0 missing, -1 invalid, -2 I/O. No contents escape on failure. */
static int read_key(const char *path, uint8_t seed[32]) {
    FIL file;
    uint8_t record[KEY_BYTES + 1];
    UINT count = 0;
    FRESULT fr = f_open(&file, path, FA_READ);
    if (fr == FR_NO_FILE || fr == FR_NO_PATH) return 0;
    if (fr != FR_OK) return -2;
    fr = f_read(&file, record, sizeof(record), &count);
    FRESULT closed = f_close(&file);
    int result = -1;
    if (fr != FR_OK || closed != FR_OK) result = -2;
    else if (count == KEY_BYTES && !memcmp(record, magic, sizeof(magic))) {
        uint32_t crc = checksum(record, 40);
        uint32_t stored = (uint32_t)record[40] | (uint32_t)record[41] << 8 |
                          (uint32_t)record[42] << 16 | (uint32_t)record[43] << 24;
        if (crc == stored) { memcpy(seed, record + 8, 32); result = 1; }
    }
    memset(record, 0, sizeof(record));
    return result;
}

bool ssh_identity_load(uint8_t seed[32], bool (*random_bytes)(uint8_t *, size_t)) {
    memset(seed, 0, 32);
    int found = read_key(KEY_PATH, seed);
    if (found == 1) { last_error = NULL; return true; }
    if (found < 0) {
        last_error = found == -1 ? "Invalid /ssh.key; restore or remove it" : "Cannot read /ssh.key";
        return false;
    }
    /* Recover a fully written first-boot key after power loss before rename.
     * Never replace a published identity with newly generated bytes. */
    found = read_key(TEMP_PATH, seed);
    if (found == -2) { last_error = "Cannot read /ssh-key.tmp"; return false; }
    if (found == 1) {
        if (f_rename(TEMP_PATH, KEY_PATH) == FR_OK) { last_error = NULL; return true; }
        memset(seed, 0, 32); last_error = "Cannot finish saving SSH key"; return false;
    }
    uint8_t record[KEY_BYTES] = {0};
    memcpy(record, magic, sizeof(magic));
    if (!random_bytes || !random_bytes(record + 8, 32)) {
        memset(record, 0, sizeof(record)); last_error = "SSH random source unavailable"; return false;
    }
    uint32_t crc = checksum(record, 40);
    for (unsigned i = 0; i < 4; ++i) record[40 + i] = (uint8_t)(crc >> (8 * i));
    FIL file;
    UINT count = 0;
    FRESULT fr = f_open(&file, TEMP_PATH, FA_WRITE | FA_CREATE_ALWAYS);
    bool ok = false;
    if (fr == FR_OK) {
        fr = f_write(&file, record, sizeof(record), &count);
        FRESULT synced = fr == FR_OK && count == sizeof(record) ? f_sync(&file) : FR_DISK_ERR;
        FRESULT closed = f_close(&file);
        ok = fr == FR_OK && count == sizeof(record) && synced == FR_OK && closed == FR_OK;
        if (ok) ok = f_rename(TEMP_PATH, KEY_PATH) == FR_OK;
    }
    if (ok) {
        uint8_t verified[32];
        ok = read_key(KEY_PATH, verified) == 1 && !memcmp(verified, record + 8, 32);
        if (ok) memcpy(seed, verified, 32);
        memset(verified, 0, sizeof(verified));
    }
    memset(record, 0, sizeof(record));
    last_error = ok ? NULL : "Cannot save SSH key to data volume";
    return ok;
}

const char *ssh_identity_error(void) { return last_error; }
